//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonFake_SITE.AmazonFakeServiceAlt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmazonFakeServiceAlt.I_Base_Datos")]
    public interface I_Base_Datos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        string Conectar_Base_Datos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Mostrar_Informacion", ReplyAction="http://tempuri.org/I_Base_Datos/Mostrar_InformacionResponse")]
        System.Data.DataTable Mostrar_Informacion(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Mostrar_Informacion", ReplyAction="http://tempuri.org/I_Base_Datos/Mostrar_InformacionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Mostrar_InformacionAsync(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Envio_Correo_Cliente", ReplyAction="http://tempuri.org/I_Base_Datos/Envio_Correo_ClienteResponse")]
        void Envio_Correo_Cliente(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Envio_Correo_Cliente", ReplyAction="http://tempuri.org/I_Base_Datos/Envio_Correo_ClienteResponse")]
        System.Threading.Tasks.Task Envio_Correo_ClienteAsync(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_Base_DatosChannel : AmazonFake_SITE.AmazonFakeServiceAlt.I_Base_Datos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_Base_DatosClient : System.ServiceModel.ClientBase<AmazonFake_SITE.AmazonFakeServiceAlt.I_Base_Datos>, AmazonFake_SITE.AmazonFakeServiceAlt.I_Base_Datos {
        
        public I_Base_DatosClient() {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Conectar_Base_Datos() {
            return base.Channel.Conectar_Base_Datos();
        }
        
        public System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync() {
            return base.Channel.Conectar_Base_DatosAsync();
        }
        
        public System.Data.DataTable Mostrar_Informacion(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos) {
            return base.Channel.Mostrar_Informacion(Nombre_StoreProcedure_BaseDatos, Nombre_Tabla_BaseDatos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Mostrar_InformacionAsync(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos) {
            return base.Channel.Mostrar_InformacionAsync(Nombre_StoreProcedure_BaseDatos, Nombre_Tabla_BaseDatos);
        }
        
        public void Envio_Correo_Cliente(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje) {
            base.Channel.Envio_Correo_Cliente(Correo_Target, Correo_Source, Correo_Encabezado, Correo_Mensaje);
        }
        
        public System.Threading.Tasks.Task Envio_Correo_ClienteAsync(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje) {
            return base.Channel.Envio_Correo_ClienteAsync(Correo_Target, Correo_Source, Correo_Encabezado, Correo_Mensaje);
        }
    }
}
