//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonFake_SITE.AmazonFakeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cls_Usuarios_DAL", Namespace="http://schemas.datacontract.org/2004/07/DAL.Usuarios")]
    [System.SerializableAttribute()]
    public partial class Cls_Usuarios_DAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SNombrePerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BEstado {
            get {
                return this.BEstadoField;
            }
            set {
                if ((this.BEstadoField.Equals(value) != true)) {
                    this.BEstadoField = value;
                    this.RaisePropertyChanged("BEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IPerfil {
            get {
                return this.IPerfilField;
            }
            set {
                if ((this.IPerfilField.Equals(value) != true)) {
                    this.IPerfilField = value;
                    this.RaisePropertyChanged("IPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SCorreo {
            get {
                return this.SCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.SCorreoField, value) != true)) {
                    this.SCorreoField = value;
                    this.RaisePropertyChanged("SCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDireccion {
            get {
                return this.SDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SDireccionField, value) != true)) {
                    this.SDireccionField = value;
                    this.RaisePropertyChanged("SDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIdentificacion {
            get {
                return this.SIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.SIdentificacionField, value) != true)) {
                    this.SIdentificacionField = value;
                    this.RaisePropertyChanged("SIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNombre {
            get {
                return this.SNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SNombreField, value) != true)) {
                    this.SNombreField = value;
                    this.RaisePropertyChanged("SNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SNombrePerfil {
            get {
                return this.SNombrePerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.SNombrePerfilField, value) != true)) {
                    this.SNombrePerfilField = value;
                    this.RaisePropertyChanged("SNombrePerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPassword {
            get {
                return this.SPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SPasswordField, value) != true)) {
                    this.SPasswordField = value;
                    this.RaisePropertyChanged("SPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SRespuesta {
            get {
                return this.SRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.SRespuestaField, value) != true)) {
                    this.SRespuestaField = value;
                    this.RaisePropertyChanged("SRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STelefono {
            get {
                return this.STelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.STelefonoField, value) != true)) {
                    this.STelefonoField = value;
                    this.RaisePropertyChanged("STelefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmazonFakeService.I_Base_Datos")]
    public interface I_Base_Datos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        string Conectar_Base_Datos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Envio_Correo_Cliente", ReplyAction="http://tempuri.org/I_Base_Datos/Envio_Correo_ClienteResponse")]
        void Envio_Correo_Cliente(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Envio_Correo_Cliente", ReplyAction="http://tempuri.org/I_Base_Datos/Envio_Correo_ClienteResponse")]
        System.Threading.Tasks.Task Envio_Correo_ClienteAsync(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Mostrar_Informacion", ReplyAction="http://tempuri.org/I_Base_Datos/Mostrar_InformacionResponse")]
        System.Data.DataTable Mostrar_Informacion(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Mostrar_Informacion", ReplyAction="http://tempuri.org/I_Base_Datos/Mostrar_InformacionResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Mostrar_InformacionAsync(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/ListarDatos", ReplyAction="http://tempuri.org/I_Base_Datos/ListarDatosResponse")]
        AmazonFake_SITE.AmazonFakeService.ListarDatosResponse ListarDatos(AmazonFake_SITE.AmazonFakeService.ListarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/ListarDatos", ReplyAction="http://tempuri.org/I_Base_Datos/ListarDatosResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.ListarDatosResponse> ListarDatosAsync(AmazonFake_SITE.AmazonFakeService.ListarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/FiltrarDatos", ReplyAction="http://tempuri.org/I_Base_Datos/FiltrarDatosResponse")]
        AmazonFake_SITE.AmazonFakeService.FiltrarDatosResponse FiltrarDatos(AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/FiltrarDatos", ReplyAction="http://tempuri.org/I_Base_Datos/FiltrarDatosResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.FiltrarDatosResponse> FiltrarDatosAsync(AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Insertar_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Insertar_DatosSinIdentityResponse")]
        AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityResponse Insertar_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Insertar_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Insertar_DatosSinIdentityResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityResponse> Insertar_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Modifica_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Modifica_DatosSinIdentityResponse")]
        AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityResponse Modifica_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Modifica_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Modifica_DatosSinIdentityResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityResponse> Modifica_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Eliminar_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Eliminar_DatosSinIdentityResponse")]
        AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityResponse Eliminar_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Eliminar_DatosSinIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Eliminar_DatosSinIdentityResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityResponse> Eliminar_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Insertar_DatosConIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Insertar_DatosConIdentityResponse")]
        AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityResponse Insertar_DatosConIdentity(AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Insertar_DatosConIdentity", ReplyAction="http://tempuri.org/I_Base_Datos/Insertar_DatosConIdentityResponse")]
        System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityResponse> Insertar_DatosConIdentityAsync(AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Login", ReplyAction="http://tempuri.org/I_Base_Datos/LoginResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> Login(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Login", ReplyAction="http://tempuri.org/I_Base_Datos/LoginResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> LoginAsync(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Change_Password", ReplyAction="http://tempuri.org/I_Base_Datos/Change_PasswordResponse")]
        string Change_Password(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Change_Password", ReplyAction="http://tempuri.org/I_Base_Datos/Change_PasswordResponse")]
        System.Threading.Tasks.Task<string> Change_PasswordAsync(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Password_Restore", ReplyAction="http://tempuri.org/I_Base_Datos/Password_RestoreResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> Password_Restore(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Password_Restore", ReplyAction="http://tempuri.org/I_Base_Datos/Password_RestoreResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> Password_RestoreAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Lock_User_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Lock_User_AccountResponse")]
        string Lock_User_Account(string correo, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Lock_User_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Lock_User_AccountResponse")]
        System.Threading.Tasks.Task<string> Lock_User_AccountAsync(string correo, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_User_Status", ReplyAction="http://tempuri.org/I_Base_Datos/View_User_StatusResponse")]
        bool View_User_Status(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_User_Status", ReplyAction="http://tempuri.org/I_Base_Datos/View_User_StatusResponse")]
        System.Threading.Tasks.Task<bool> View_User_StatusAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Create_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Create_AccountResponse")]
        string Create_Account(string correo, string nombre, string pssword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Create_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Create_AccountResponse")]
        System.Threading.Tasks.Task<string> Create_AccountAsync(string correo, string nombre, string pssword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Create_Employee_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Create_Employee_AccountResponse")]
        string Create_Employee_Account(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Create_Employee_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Create_Employee_AccountResponse")]
        System.Threading.Tasks.Task<string> Create_Employee_AccountAsync(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Delete_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Delete_AccountResponse")]
        string Delete_Account(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Delete_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Delete_AccountResponse")]
        System.Threading.Tasks.Task<string> Delete_AccountAsync(string correo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Delete_User_Account_Por_Admin", ReplyAction="http://tempuri.org/I_Base_Datos/Delete_User_Account_Por_AdminResponse")]
        string Delete_User_Account_Por_Admin(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Delete_User_Account_Por_Admin", ReplyAction="http://tempuri.org/I_Base_Datos/Delete_User_Account_Por_AdminResponse")]
        System.Threading.Tasks.Task<string> Delete_User_Account_Por_AdminAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Update_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Update_AccountResponse")]
        string Update_Account(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Update_Account", ReplyAction="http://tempuri.org/I_Base_Datos/Update_AccountResponse")]
        System.Threading.Tasks.Task<string> Update_AccountAsync(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Email_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_Email_AdminsResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Email_Admins(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Email_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_Email_AdminsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Email_AdminsAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Name_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_Name_AdminsResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Name_Admins(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Name_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_Name_AdminsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Name_AdminsAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_ID_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_ID_AdminsResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_ID_Admins(string Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_ID_Admins", ReplyAction="http://tempuri.org/I_Base_Datos/View_ID_AdminsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_ID_AdminsAsync(string Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Email_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_Email_UsersResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Email_Users(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Email_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_Email_UsersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Email_UsersAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Name_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_Name_UsersResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Name_Users(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_Name_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_Name_UsersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Name_UsersAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_ID_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_ID_UsersResponse")]
        System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_ID_Users(string Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/View_ID_Users", ReplyAction="http://tempuri.org/I_Base_Datos/View_ID_UsersResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_ID_UsersAsync(string Identificacion);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public ListarDatosRequest() {
        }
        
        public ListarDatosRequest(string sNombreSP, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public ListarDatosResponse() {
        }
        
        public ListarDatosResponse(System.Data.DataTable ListarDatosResult, string SMsError) {
            this.ListarDatosResult = ListarDatosResult;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sNombreParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.SqlDbType DbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sValrParametro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SMsError;
        
        public FiltrarDatosRequest() {
        }
        
        public FiltrarDatosRequest(string sNombreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValrParametro, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.sNombreParametro = sNombreParametro;
            this.DbType = DbType;
            this.sValrParametro = sValrParametro;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FiltrarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FiltrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable FiltrarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public FiltrarDatosResponse() {
        }
        
        public FiltrarDatosResponse(System.Data.DataTable FiltrarDatosResult, string SMsError) {
            this.FiltrarDatosResult = FiltrarDatosResult;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosSinIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosSinIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMsError;
        
        public Insertar_DatosSinIdentityRequest() {
        }
        
        public Insertar_DatosSinIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosSinIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosSinIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Insertar_DatosSinIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public Insertar_DatosSinIdentityResponse() {
        }
        
        public Insertar_DatosSinIdentityResponse(bool Insertar_DatosSinIdentityResult, string SMsError) {
            this.Insertar_DatosSinIdentityResult = Insertar_DatosSinIdentityResult;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_DatosSinIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosSinIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMsError;
        
        public Modifica_DatosSinIdentityRequest() {
        }
        
        public Modifica_DatosSinIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modifica_DatosSinIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modifica_DatosSinIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Modifica_DatosSinIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public Modifica_DatosSinIdentityResponse() {
        }
        
        public Modifica_DatosSinIdentityResponse(bool Modifica_DatosSinIdentityResult, string SMsError) {
            this.Modifica_DatosSinIdentityResult = Modifica_DatosSinIdentityResult;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_DatosSinIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Eliminar_DatosSinIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMsError;
        
        public Eliminar_DatosSinIdentityRequest() {
        }
        
        public Eliminar_DatosSinIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Eliminar_DatosSinIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Eliminar_DatosSinIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Eliminar_DatosSinIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SMsError;
        
        public Eliminar_DatosSinIdentityResponse() {
        }
        
        public Eliminar_DatosSinIdentityResponse(bool Eliminar_DatosSinIdentityResult, string SMsError) {
            this.Eliminar_DatosSinIdentityResult = Eliminar_DatosSinIdentityResult;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosConIdentity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosConIdentityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable dtParametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SMsError;
        
        public Insertar_DatosConIdentityRequest() {
        }
        
        public Insertar_DatosConIdentityRequest(string sNombreSP, System.Data.DataTable dtParametros, string sValorScalar, string SMsError) {
            this.sNombreSP = sNombreSP;
            this.dtParametros = dtParametros;
            this.sValorScalar = sValorScalar;
            this.SMsError = SMsError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insertar_DatosConIdentityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insertar_DatosConIdentityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Insertar_DatosConIdentityResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sValorScalar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SMsError;
        
        public Insertar_DatosConIdentityResponse() {
        }
        
        public Insertar_DatosConIdentityResponse(bool Insertar_DatosConIdentityResult, string sValorScalar, string SMsError) {
            this.Insertar_DatosConIdentityResult = Insertar_DatosConIdentityResult;
            this.sValorScalar = sValorScalar;
            this.SMsError = SMsError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_Base_DatosChannel : AmazonFake_SITE.AmazonFakeService.I_Base_Datos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_Base_DatosClient : System.ServiceModel.ClientBase<AmazonFake_SITE.AmazonFakeService.I_Base_Datos>, AmazonFake_SITE.AmazonFakeService.I_Base_Datos {
        
        public I_Base_DatosClient() {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Conectar_Base_Datos() {
            return base.Channel.Conectar_Base_Datos();
        }
        
        public System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync() {
            return base.Channel.Conectar_Base_DatosAsync();
        }
        
        public void Envio_Correo_Cliente(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje) {
            base.Channel.Envio_Correo_Cliente(Correo_Target, Correo_Source, Correo_Encabezado, Correo_Mensaje);
        }
        
        public System.Threading.Tasks.Task Envio_Correo_ClienteAsync(string Correo_Target, string Correo_Source, string Correo_Encabezado, string Correo_Mensaje) {
            return base.Channel.Envio_Correo_ClienteAsync(Correo_Target, Correo_Source, Correo_Encabezado, Correo_Mensaje);
        }
        
        public System.Data.DataTable Mostrar_Informacion(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos) {
            return base.Channel.Mostrar_Informacion(Nombre_StoreProcedure_BaseDatos, Nombre_Tabla_BaseDatos);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Mostrar_InformacionAsync(string Nombre_StoreProcedure_BaseDatos, string Nombre_Tabla_BaseDatos) {
            return base.Channel.Mostrar_InformacionAsync(Nombre_StoreProcedure_BaseDatos, Nombre_Tabla_BaseDatos);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.ListarDatosResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.ListarDatos(AmazonFake_SITE.AmazonFakeService.ListarDatosRequest request) {
            return base.Channel.ListarDatos(request);
        }
        
        public System.Data.DataTable ListarDatos(string sNombreSP, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.ListarDatosRequest inValue = new AmazonFake_SITE.AmazonFakeService.ListarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.ListarDatosResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).ListarDatos(inValue);
            SMsError = retVal.SMsError;
            return retVal.ListarDatosResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.ListarDatosResponse> ListarDatosAsync(AmazonFake_SITE.AmazonFakeService.ListarDatosRequest request) {
            return base.Channel.ListarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.FiltrarDatosResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.FiltrarDatos(AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatos(request);
        }
        
        public System.Data.DataTable FiltrarDatos(string sNombreSP, string sNombreParametro, System.Data.SqlDbType DbType, string sValrParametro, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest inValue = new AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.sNombreParametro = sNombreParametro;
            inValue.DbType = DbType;
            inValue.sValrParametro = sValrParametro;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.FiltrarDatosResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).FiltrarDatos(inValue);
            SMsError = retVal.SMsError;
            return retVal.FiltrarDatosResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.FiltrarDatosResponse> FiltrarDatosAsync(AmazonFake_SITE.AmazonFakeService.FiltrarDatosRequest request) {
            return base.Channel.FiltrarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.Insertar_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest request) {
            return base.Channel.Insertar_DatosSinIdentity(request);
        }
        
        public bool Insertar_DatosSinIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest inValue = new AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).Insertar_DatosSinIdentity(inValue);
            SMsError = retVal.SMsError;
            return retVal.Insertar_DatosSinIdentityResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityResponse> Insertar_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Insertar_DatosSinIdentityRequest request) {
            return base.Channel.Insertar_DatosSinIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.Modifica_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest request) {
            return base.Channel.Modifica_DatosSinIdentity(request);
        }
        
        public bool Modifica_DatosSinIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest inValue = new AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).Modifica_DatosSinIdentity(inValue);
            SMsError = retVal.SMsError;
            return retVal.Modifica_DatosSinIdentityResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityResponse> Modifica_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Modifica_DatosSinIdentityRequest request) {
            return base.Channel.Modifica_DatosSinIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.Eliminar_DatosSinIdentity(AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest request) {
            return base.Channel.Eliminar_DatosSinIdentity(request);
        }
        
        public bool Eliminar_DatosSinIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest inValue = new AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).Eliminar_DatosSinIdentity(inValue);
            SMsError = retVal.SMsError;
            return retVal.Eliminar_DatosSinIdentityResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityResponse> Eliminar_DatosSinIdentityAsync(AmazonFake_SITE.AmazonFakeService.Eliminar_DatosSinIdentityRequest request) {
            return base.Channel.Eliminar_DatosSinIdentityAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityResponse AmazonFake_SITE.AmazonFakeService.I_Base_Datos.Insertar_DatosConIdentity(AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest request) {
            return base.Channel.Insertar_DatosConIdentity(request);
        }
        
        public bool Insertar_DatosConIdentity(string sNombreSP, System.Data.DataTable dtParametros, ref string sValorScalar, ref string SMsError) {
            AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest inValue = new AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.dtParametros = dtParametros;
            inValue.sValorScalar = sValorScalar;
            inValue.SMsError = SMsError;
            AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityResponse retVal = ((AmazonFake_SITE.AmazonFakeService.I_Base_Datos)(this)).Insertar_DatosConIdentity(inValue);
            sValorScalar = retVal.sValorScalar;
            SMsError = retVal.SMsError;
            return retVal.Insertar_DatosConIdentityResult;
        }
        
        public System.Threading.Tasks.Task<AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityResponse> Insertar_DatosConIdentityAsync(AmazonFake_SITE.AmazonFakeService.Insertar_DatosConIdentityRequest request) {
            return base.Channel.Insertar_DatosConIdentityAsync(request);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> Login(string correo, string password) {
            return base.Channel.Login(correo, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> LoginAsync(string correo, string password) {
            return base.Channel.LoginAsync(correo, password);
        }
        
        public string Change_Password(string correo, string password) {
            return base.Channel.Change_Password(correo, password);
        }
        
        public System.Threading.Tasks.Task<string> Change_PasswordAsync(string correo, string password) {
            return base.Channel.Change_PasswordAsync(correo, password);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> Password_Restore(string correo) {
            return base.Channel.Password_Restore(correo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> Password_RestoreAsync(string correo) {
            return base.Channel.Password_RestoreAsync(correo);
        }
        
        public string Lock_User_Account(string correo, bool Estado) {
            return base.Channel.Lock_User_Account(correo, Estado);
        }
        
        public System.Threading.Tasks.Task<string> Lock_User_AccountAsync(string correo, bool Estado) {
            return base.Channel.Lock_User_AccountAsync(correo, Estado);
        }
        
        public bool View_User_Status(string Correo) {
            return base.Channel.View_User_Status(Correo);
        }
        
        public System.Threading.Tasks.Task<bool> View_User_StatusAsync(string Correo) {
            return base.Channel.View_User_StatusAsync(Correo);
        }
        
        public string Create_Account(string correo, string nombre, string pssword) {
            return base.Channel.Create_Account(correo, nombre, pssword);
        }
        
        public System.Threading.Tasks.Task<string> Create_AccountAsync(string correo, string nombre, string pssword) {
            return base.Channel.Create_AccountAsync(correo, nombre, pssword);
        }
        
        public string Create_Employee_Account(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono, string Password) {
            return base.Channel.Create_Employee_Account(Correo, Nombre, Identificacion, Direccion, Telefono, Password);
        }
        
        public System.Threading.Tasks.Task<string> Create_Employee_AccountAsync(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono, string Password) {
            return base.Channel.Create_Employee_AccountAsync(Correo, Nombre, Identificacion, Direccion, Telefono, Password);
        }
        
        public string Delete_Account(string correo, string password) {
            return base.Channel.Delete_Account(correo, password);
        }
        
        public System.Threading.Tasks.Task<string> Delete_AccountAsync(string correo, string password) {
            return base.Channel.Delete_AccountAsync(correo, password);
        }
        
        public string Delete_User_Account_Por_Admin(string correo) {
            return base.Channel.Delete_User_Account_Por_Admin(correo);
        }
        
        public System.Threading.Tasks.Task<string> Delete_User_Account_Por_AdminAsync(string correo) {
            return base.Channel.Delete_User_Account_Por_AdminAsync(correo);
        }
        
        public string Update_Account(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono) {
            return base.Channel.Update_Account(Correo, Nombre, Identificacion, Direccion, Telefono);
        }
        
        public System.Threading.Tasks.Task<string> Update_AccountAsync(string Correo, string Nombre, string Identificacion, string Direccion, string Telefono) {
            return base.Channel.Update_AccountAsync(Correo, Nombre, Identificacion, Direccion, Telefono);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Email_Admins(string Correo) {
            return base.Channel.View_Email_Admins(Correo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Email_AdminsAsync(string Correo) {
            return base.Channel.View_Email_AdminsAsync(Correo);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Name_Admins(string Nombre) {
            return base.Channel.View_Name_Admins(Nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Name_AdminsAsync(string Nombre) {
            return base.Channel.View_Name_AdminsAsync(Nombre);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_ID_Admins(string Identificacion) {
            return base.Channel.View_ID_Admins(Identificacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_ID_AdminsAsync(string Identificacion) {
            return base.Channel.View_ID_AdminsAsync(Identificacion);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Email_Users(string Correo) {
            return base.Channel.View_Email_Users(Correo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Email_UsersAsync(string Correo) {
            return base.Channel.View_Email_UsersAsync(Correo);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_Name_Users(string Nombre) {
            return base.Channel.View_Name_Users(Nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_Name_UsersAsync(string Nombre) {
            return base.Channel.View_Name_UsersAsync(Nombre);
        }
        
        public System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL> View_ID_Users(string Identificacion) {
            return base.Channel.View_ID_Users(Identificacion);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.Collection<AmazonFake_SITE.AmazonFakeService.Cls_Usuarios_DAL>> View_ID_UsersAsync(string Identificacion) {
            return base.Channel.View_ID_UsersAsync(Identificacion);
        }
    }
}
