//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonFake_SITE.AmazonFakeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AmazonFakeService.I_Base_Datos")]
    public interface I_Base_Datos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        string Conectar_Base_Datos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_Base_Datos/Conectar_Base_Datos", ReplyAction="http://tempuri.org/I_Base_Datos/Conectar_Base_DatosResponse")]
        System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_Base_DatosChannel : AmazonFake_SITE.AmazonFakeService.I_Base_Datos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_Base_DatosClient : System.ServiceModel.ClientBase<AmazonFake_SITE.AmazonFakeService.I_Base_Datos>, AmazonFake_SITE.AmazonFakeService.I_Base_Datos {
        
        public I_Base_DatosClient() {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_Base_DatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Conectar_Base_Datos() {
            return base.Channel.Conectar_Base_Datos();
        }
        
        public System.Threading.Tasks.Task<string> Conectar_Base_DatosAsync() {
            return base.Channel.Conectar_Base_DatosAsync();
        }
    }
}
